# ATTENTION !!! Rebuild les container s'il y a des changements dans le code ?
# Dans un environnement de dev il faudrait lier un volume (probablement complètement séparer notre repo de travail ?)

services: 
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # Récupérer là où sont stockés les certificats certbots
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  app:

    build:
      context: .
      dockerfile: Dockerfile.app
    
    env_file: ".env"
    ports:
      - 3000:3000
    depends_on:
      - db
    container_name: pfc-application
  
  db:
    image: postgres
    container_name: pfc-database
    environment:
      - POSTGRES_USER=pfcadmin
      - POSTGRES_PASSWORD=pfc
      - POSTGRES_DB=pfc
    volumes: 
      - ./src/database:/docker-entrypoint-initdb.d
      - pg-pfc:/var/lib/postgresql/data
volumes:
  pg-pfc: 
